#Marcos Cerdán Amat 20518142-A

OPTS = -Wall -O3 -std=c++0x

maxsum-greedy: maxsum-greedy.cc
	g++ ${OPTS} maxsum-greedy.cc -o maxsum-greedy
tar: maxsum-greedy.cc
	tar cvfz 20518142A.tar.gz maxsum-greedy.cc makefile